- gosrc/deps-tree.go
the code under `gosrc/deps-tree.go` is based on https://github.com/KyleBanks/depth which is MIT licensed
> chore: add github.com/KyleBanks/depth MIT license

- lib/index.js
- test/inspect.test.js
- test/system/fixtures/gopath/src/github.com/prometheus/prometheus-cmd-prometheus-expected-list.json
- test/system/fixtures/gopath/src/with-k8s-client/expected-list.json
currently the backend compares the root to the vulndb too,
and 0.0.0 may trigger a vuln, altough we don't know the actual version
> fix: instead of 0.0.0 set root version to ''

- gosrc/resolver/dirwalk/dirwalk.go
- test/fixtures/gopath/src/path/to/multiroot-pkg/shouldskip/_underscore_folder/main.go
to better resemble the behaviour of dep:
https://github.com/golang/dep/blob/80e94e8eef3660a2cd9d80b64ae95d7c898e8453/gps/pkgtree/reachmap.go#L26
> fix: dirwalk: skip dirs starting with _

- lib/index.js
- test/inspect.test.js
> fix: better suggest `govendor` users to run `sync`

- lib/index.js
- test/inspect.test.js
as the backend doesn't need it anymore,
and it reduces the result json size by 3
> feat: don't include `from` arrays in tree

- package.json
to fix an issue with build-stages
> chore: update semantic-release to ^8

- lib/index.js
- package.json
What does this PR do?
Adding assets to the binary release (by path.join(__dirname,PATH))
Dump all of the files to the disk (temp folder)
Execute the go script (resolve-deps.go) from the temp dir
This is the new behaviour of the plugin regarding if it run as binary \ not
How should this be manually tested?
No auto tests were added.
Manually tested "pkg ." (Zeit) with node 8 on the following os:
-Mac
-Windows
Any background context you want to provide?
Trying to avoid creating a docker img for python, we realised it might be faster to use Zeit binary release as a proper solution
> add go files as Zeit assets, dump them to disk and run

- lib/index.js
Added missing check in error handler.
Output from CLI before:
```
Testing /Users/kirill/Work/golang-app...
Cannot read property 'removeCallback' of undefined
```
Output from CLI after:
```
Testing /Users/kirill/Work/golang-app...
failed parsing Gopkg.toml: ENOENT: no such file or directory, open '/Users/kirill/Work/golang-app/Gopkg.toml'
```
> fix: added missing check in error handler

- .travis.yml
- lib/index.ts
- package.json
- test/manual.ts
- test/with-symlink.test.ts
Supersedes https://github.com/snyk/snyk-go-plugin/pull/36
Since the manifest parsing logic has now been separated into snyk-go-parser, it makes sense for the plugin to re-use that.
Drive-by: robustify tests, clean up the build script.
Scanning Go projects via CLI.
> refactor: reuse the logic from snyk-go-parser

- package.json
parser release: https://github.com/snyk/snyk-go-parser/releases/tag/v1.0.0
> fix: lock go parser version

- lib/index.ts
At the moment, the targetFile is not properly parsed, as targetFile can be a path, e.g. "/project/go.mod". In this case line 128 would not result in "gomodules", although this is desired.
`snyk test --file=project/go.mod`
At the moment, `snyk test --file=` with a path, results in '/project/go.mod' not supported, while this is already supported.
> fix: proper parsing of gomodules targetFile

- lib/index.ts
- test/fixtures/golist/empty/expected-tree.json
- test/fixtures/golist/import/expected-tree.json
- test/fixtures/gomod-small/expected-tree.json
For the default name, basepath is more suitable then just dot. Version
is better 0.0.0 than unknown and project name can be taken from main
module path.
Some minor fixes for better name and version.
Running `snyk monitor` agains `go.mod` project and checking the result.
https://github.com/snyk/snyk-go-plugin/compare/fix/name-and-version?expand=1#diff-13b5b151431c7e7a17f273559ed212d5R476 is awful, but I can't think of anything better (without using lodash). Feel free to suggest changes.
> fix: default name, unknown version, name from main

- lib/errors/custom-error.ts
- lib/index.ts
- test/fixtures/gomod-small-failing/go.mod
- test/inspect.test.ts
Added new gomod-small-failing test fixture - with invalid go.mod
Added inspect test for expected error messages when 'go list' fails
Added custom error class
Throw custom error from when 'go list' fails
Fix error messages for go modules when 'go list' fails
npm run test
https://snyk.slack.com/archives/CGV4DV5R7/p1568833750016600
https://snyksec.atlassian.net/browse/BST-883
new example error message:
> fix: improve error messages for go modules

- .travis.yml
- lib/index.ts
Go 1.13 introduced some changes to how GOPATH is handled (https://golang.org/doc/go1.13#modules), so worth updating our test matrix with this version.
To not increase the matrix, replacing 1.9.x with 1.10.x.
Not going straight for 1.11.x to keep a pre-go-modules version in the matrix.
This PR also fixes a typescript compilation error.
> Test/go 1.13

- .travis.yml
Go 1.14 was released with various changes to `go modules` mentioned in the release notes: https://golang.org/doc/go1.14
this PR makes sure it's in the test matrix
> test: add go 1.14 to test matrix (replacing 1.12)

- lib/index.ts
In order to improve performance and avoid `JavaScript heap out of memory` errors replace `for..of` with the classic `for` loop
Noticed issue while was investigating 2 similar issues with the go projects: snyk monitor failed for them with the same error and stack traces were identical 
More to read about loops:
https://medium.com/@TravCav/why-reverse-loops-are-faster-a09d65473006
https://medium.com/tech-tajawal/loops-performances-in-node-js-9fbccf2d6aa6
> fix: replace for..of with reverse for

- lib/index.ts
- package.json
- test/fixtures/golist/empty/expected-depgraph.json
- test/fixtures/golist/empty/expected-tree.json
- test/fixtures/golist/import/expected-depgraph.json
- test/fixtures/golist/import/expected-tree.json
- test/fixtures/gomod-small/expected-gomodules-depgraph.json
- test/golist.test.ts
- test/inspect.test.ts
Add support of dep-graph for go-modules and dropping dep-tree
depends of https://github.com/snyk/snyk-go-plugin/pull/73 [depGraph library supports only node v8+] ✅
> feat: add support dep-graph gomodules and drop deptree

- lib/index.ts
- package.json
Updating dep-graph to prevent including our lodash fork.
HAMMER-99
> fix: update dep-graph to use upstream lodash

- .circleci/config.yml
- Allow releases to actually work
- `tsc` was not available during npm "publish" due to `NODE_ENV`
- This is a library, not a service
> chore: Enable releasing

- .circleci/config.yml
> chore: fix release step in circle ci

- lib/sub-process.ts
Removes an error that prevents this tool from running within the VSCode integrated terminal. This error was added three years ago and it no longer appears to be an issue.
`lib/sub-process.ts`
1. Install this into a local copy of Snyk CLI
2. Open up a Go project with VSCode
3. Open up the integrated terminal within that window
4. Run `snyk test` with your modified Snyk CLI
Screenshot of this modification running in the VSCode integrated terminal:
> fix: remove error for vscode terminal

- lib/sub-process.ts
- test/with-symlink.test.ts
Disable the shell for child processes.
> fix: disable shell for child processes

- lib/index.ts
- package.json
Adds meaningul error message when golang's binary is not available on the host system.
> fix: go binary explicit error

- test/system/system.test.ts
Adjust the tests related to `govendor` to use only versions of `golang` which are lower than `1.16`.
Soon we will start the deprecation of `govendor` support from our product.
> fix: bind govendor tests to specific version range

- lib/sub-process.ts
Fix missing intialization of 'spawnOptions.env'
> fix: default initialization for env

- .circleci/config.yml
Update the node runtime version from 14 to 18 for the release step, which was required by a dependency.
> fix: upgrade node version in release workflow

- lib/index.ts
- package.json
This bumps the snyk-go-parser version to 1.13.0 - for more info see here https://github.com/snyk/snyk-go-parser/pull/45
> feat: bump go parser v1.13.0
