gosrc/resolver/resolver.go
Hello !
I just found a little typo in your code while using the Go CLI to upload a Gopkg file.
Thank you !
=> Fix GOPATH Typo

appveyor.yml, package.json, test/inspect.test.js, test/system/system.test.js
Adding AppVeyor to cover Windows-based testing
=> test: appveyor init

lib/index.ts
The build graph to tree conversion was excessively slow on big projects due to repeated copies/merges of the maps.
This PR simplifies the counter algorithm to its bare essence.
WAS:
- at each node of the graph...
- check parentCount + curentCount for the dep
- when processing child nodes recursively, pass parentCount + currentCount as parentCount
- after processing the child, merge child.currentCount into currentCount
NOW:
- just have a single mutable totalCount for all the deps
The algorithms are equivalent. The second is much much faster. (13 min -> 3 sec for one of the customers)
https://snyksec.atlassian.net/browse/BST-593
=> fix: simplify package repetition counter

lib/index.ts
A large project (e.g. CockroachDB) has an import tree consisting of a huge number of its sub-packages. Scanning that tree can lead to timeouts.
We already have a mechanism to bail early on frequently used external packages. By extending it to subpackages, we preserve the dependencies and terminate the tree scanning early.
Drive by: improved comments (chatted with @michael-go to find out the reasoning behind the design).
=> fix: optimize scanning of large projects

lib/index.ts, test/fixtures/golist/empty/expected-tree.json, test/fixtures/golist/import/expected-tree.json, test/fixtures/golist/import/go.mod, test/fixtures/golist/import/resolve-deps.go, test/fixtures/golist/import/resolver/dirwalk/dirwalk.go, test/fixtures/golist/import/resolver/graph/graph.go, test/fixtures/golist/import/resolver/pkg.go, test/fixtures/golist/import/resolver/resolver.go, test/golist.test.ts
Using `go list -json ./...`, produces all imported packages within a go project.
`test/golist.test.ts`
https://snyksec.atlassian.net/browse/BST-650
=> feat: get packages import using go list

lib/index.ts, package.json
Unifying packange manager naming, so it's consistent through the system
=> fix: unify package manager naming

package.json
Add the missing `tslib` package
Helps resolve https://github.com/snyk/snyk/issues/667
=> feat: add missing tslib package

.github/CODEOWNERS
=> chore: add boost as code owners

package.json, test/fixtures/gomod-small/expected-tree.json
Bump version after https://github.com/snyk/snyk-go-parser/pull/18 was fixed
=> feat: bump snyk-go-parser version to latest to fix compilation issue

lib/index.ts, test/inspect.test.ts
=> fix: take into account --file flag

.travis.yml
Update Node version used in semantic release
=> feat: Update Node version used in semantic release

.travis.yml, appveyor.yml, tsconfig.json
added missing yml changes, dropped unused nodejs6 on appveyor, compiler updated from es2015 to es2017
=> feat: add missing yml changes, updated to es2017

.circleci/config.yml
Making all steps as required for release step
=> chore: fix circle release requirements

.github/CODEOWNERS
=> chore/codeowners -> Loki

lib/index.ts, package.json
* Uses `@snyk/graphlib` which is our fork of `graphlib` which uses only the required packages of lodash rather than the whole thing.
* Updates `@snyk/dep-graph` which does not depend on `lodash`
https://snyk.slack.com/archives/C01MDU3UL59/p1612973794033300
=> Reduce lodash profile

lib/index.ts, test/fixtures/gomod-replace/expected-depgraph.json, test/fixtures/gomod-replace/go.mod, test/fixtures/gomod-replace/main.go, test/golist.test.ts
Adds support for [replace](https://golang.org/ref/mod#go-mod-file-replace) directive (for the cli)
=> feat: support replace directive

lib/index.ts, test/fixtures/gomod-small/expected-gomodules-depgraph.json
This adds pruning at depgraph generation for go.mod projects.
=> feat: add pruning to go mod projects at depgraph generation

.circleci/config.yml
also update release branch from master to main
=> feat: add prodsec/security_scans

lib/helpers.ts, test/helpers.test.ts
Adding another fallback mechanism. If we don't find the toolchain, we should default to the go version the client has specified in their manifest file. only if we don't find those(which should never be the case) we should fallback to the version of Go the client uses on their machine (CLI path) or the Go version we use on our side (SCM path)
=> fix: [OSM-3197] add another fallback for go std libraries

lib/index.ts, test/build-graph.test.ts
Handles root and local packages
=> fix: [OSM-3197] handle local and root packages
